openapi: 3.0.0
info:
  title: Art API
  version: 1.0.0
  description: A simple art objects API
paths:
  /art-objects:
    post:
      operationId: create_art_object
      summary: Create a new art object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  description: The title of the art object
                artist:
                  type: string
                  description: The artist who created the art object
                year:
                  type: integer
                  description: The year the art object was created
      responses:
        "201":
          description: Art object created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  artist:
                    type: string
                  year:
                    type: integer
        "400":
          description: Invalid input
    get:
      operationId: list_art_objects
      summary: List all art objects
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
          description: Maximum number of art objects to return
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
          description: Number of art objects to skip
      responses:
        "200":
          description: List of art objects
          content:
            application/json:
              schema:
                type: object
                properties:
                  art_objects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        artist:
                          type: string
                        year:
                          type: integer
                  total:
                    type: integer
  /art-objects/{art_object_id}:
    get:
      operationId: get_art_object
      summary: Get an art object by ID
      parameters:
        - name: art_object_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the art object to retrieve
      responses:
        "200":
          description: Art object retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  artist:
                    type: string
                  year:
                    type: integer
        "404":
          description: Art object not found
    put:
      operationId: update_art_object
      summary: Update an art object
      parameters:
        - name: art_object_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the art object to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                artist:
                  type: string
                year:
                  type: integer
      responses:
        "200":
          description: Art object updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  artist:
                    type: string
                  year:
                    type: integer
        "404":
          description: Art object not found
    delete:
      operationId: delete_art_object
      summary: Delete an art object
      parameters:
        - name: art_object_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the art object to delete
      responses:
        "204":
          description: Art object deleted successfully
        "404":
          description: Art object not found