openapi: 3.0.0
info:
  title: Users API v3
  version: 3.0.0
paths:
  /users/{user_id}:
    get:
      operationId: get_user
      summary: Get user by ID (v3)
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: User details with profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  profile:
                    type: object
                    properties:
                      full_name:
                        type: string
                      email:
                        type: string
                      preferences:
                        type: object